server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicles
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create






